apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-system

resources:
  - ../../local-path-provisioner/overlays/prod
  - ../../minio/overlays/prod
  - ../../nfs-server/overlays/prod
  - ../../nfs-subdir-external-provisioner/overlays/prod
  - ../../velero/overlays/prod

# Inventory and Kro graph will be added in follow-up commits.
